oci.engine.ctl=podman
oci.engine.work-directory=.

# Image building
quarkus.container-image.build=true
quarkus.container-image.name=oci-manager
quarkus.container-image.tag=${project.version}
quarkus.container-image.additional-tags=latest
quarkus.container-image.group=aiezzi
